name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Set Subscription
        run: az account set -s "${{secrets.SUBSCRIPTION_ID}}"
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["src/*.yml"]'
        env:
          TRAINING_DATA_PATH: ${{secrets.TRAINING_DATA_PATH}}
      - name: Create Job
        run: az ml job create --file 'src/job.yml' --resource-group rg-mcsm-cus-jovd --workspace-name mlw-cs-dev

  Producction:
    needs: train
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Set Subscription
        run: az account set -s "${{secrets.SUBSCRIPTION_ID}}"
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["src/*.yml"]'
        env:
          TRAINING_DATA_PATH: ${{secrets.TRAINING_DATA_PATH}}
      - name: Create Job
        run: az ml job create --file 'src/job.yml' --resource-group rg-mcsm-cus-jovd --workspace-name mlw-cs-dev